name: Reminder
packages:
  Swinject:
    url: https://github.com/Swinject/Swinject
    from: 2.8.1
  RealmCocoa:
    url: https://github.com/realm/realm-cocoa.git
    majorVersion: 10.12.0
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk
    majorVersion: 8.15.0
  GoogleSignIn:
    url: https://github.com/google/GoogleSignIn-iOS
    majorVersion: 6.1.0
  RxSwift:
    url: https://github.com/ReactiveX/RxSwift
    from: 6.5.0
  Lottie:
    url: https://github.com/airbnb/lottie-ios
    from: 3.3.0
targets:
  Reminder:
    type: application
    platform: iOS
    deploymentTarget: "13.0"
    sources: [Reminder]
    settings:
      base:
        CODE_SIGN_STYLE: Automatic
        PRODUCT_BUNDLE_IDENTIFIER: com.test.doan
        INFOPLIST_FILE: Reminder/App/Info.plist
        DEVELOPMENT_TEAM: QLJ2C34MTR
      configs:
        debug:
          CUSTOM_BUILD_SETTING: my_debug_value
          CODE_SIGN_ENTITLEMENTS: Reminder/Reminder.entitlements
        release:
          CUSTOM_BUILD_SETTING: my_release_value
    dependencies:
      - package: Swinject
      - package: RealmCocoa
        product: Realm
      - package: RealmCocoa
        product: RealmSwift
      - package: Firebase
        product: FirebaseAnalytics
      - package: Firebase
        product: FirebaseDatabase
      - package: RxSwift
        product: RxSwift
      - package: RxSwift
        product: RxCocoa
      - package: GoogleSignIn
      - package: Lottie
      - target: FSCalendar
  FSCalendar:
    type: framework
    platform: iOS
    sources: [Thirdparty/FSCalendar]
    
